set_property LOCK_PINS {I0:A4} [get_cells delay1_lut]
set_property LOCK_PINS {I0:A5} [get_cells delay2_lut]
set_property LOCK_PINS {I0:A4} [get_cells delay3_lut]
set_property LOCK_PINS {I0:A5} [get_cells delay4_lut]
set_property LOCK_PINS {I0:A4} [get_cells delay5_lut]
set_property LOCK_PINS {I0:A5} [get_cells delay6_lut]
set_property LOCK_PINS {I0:A4} [get_cells delay7_lut]
set_property LOCK_PINS {I0:A5} [get_cells delay8_lut]
set_property LOCK_PINS {I0:A6 I1:A2} [get_cells invert_lut]
set_property LOCK_PINS {I0:A6 I1:A2} [get_cells Xor_out]
set_property LOCK_PINS {I0:A2 I1:A4} [get_cells En_row_col]

set_property BEL A6LUT [get_cells {delay1_lut}]
set_property BEL B6LUT [get_cells {delay2_lut}]
set_property BEL A6LUT [get_cells {delay3_lut}]
set_property BEL B6LUT [get_cells {delay4_lut}]
set_property BEL A6LUT [get_cells {delay5_lut}]
set_property BEL B6LUT [get_cells {delay6_lut}]
set_property BEL A6LUT [get_cells {delay7_lut}]
set_property BEL B6LUT [get_cells {delay8_lut}]
set_property BEL C6LUT [get_cells {invert_lut}]
set_property BEL B6LUT [get_cells {Xor_out}]
set_property BEL A6LUT [get_cells {En_row_col}]