##auto_generate constrain code
fp = open("mix_ro.txt","w")
size_row = 9

for j in range(1,26+1):
    if(j<=20):
        fp.write("set_property LOC SLICE_X%dY198 [get_cells init_shift_col_reg[%d]] \n" % ((30+2*j),j))
    else:
        fp.write("set_property LOC SLICE_X%dY198 [get_cells init_shift_col_reg[%d]] \n" % ((2*j+44),j))

for j in range(1,size_row+1):
    fp.write("set_property LOC SLICE_X29Y%d [get_cells init_shift_row_reg[%d]] \n" % (197-(j-1)*5,j))
for j in range(size_row+1,size_row*2+1):
    fp.write("set_property LOC SLICE_X29Y%d [get_cells init_shift_row_reg[%d]] \n" % (192-(j-1)*5,j))
for j in range(size_row*2+1,size_row*3+1):
    fp.write("set_property LOC SLICE_X29Y%d [get_cells init_shift_row_reg[%d]] \n" % (187-(j-1)*5,j))

fp.write("\n")

for j in range(1,size_row+1):
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX32 CLBLM_M_C1 }  } [get_nets {Ro1[%d].ro/reset}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {Ro1[%d].ro/ring_delay1}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {Ro1[%d].ro/ring_delay3}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {Ro1[%d].ro/ring_delay5}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {Ro1[%d].ro/ring_delay7}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX35 CLBLM_M_C6 }  } [get_nets {Ro1[%d].ro/ring_delay8}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {Ro1[%d].ro/ring_delay2}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {Ro1[%d].ro/ring_delay4}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX11 CLBLM_M_A4 }  } [get_nets {Ro1[%d].ro/ring_delay6}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX4 CLBLM_M_A6 }  IMUX12 CLBLM_M_B6 }  } [get_nets {Ro1[%d].ro/ring_invert}]\n" % j)            

for j in range(size_row+1,size_row*2+1):
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX32 CLBLM_M_C1 }  } [get_nets {Ro2[%d].ro/reset}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {Ro2[%d].ro/ring_delay1}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {Ro2[%d].ro/ring_delay3}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {Ro2[%d].ro/ring_delay5}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {Ro2[%d].ro/ring_delay7}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX35 CLBLM_M_C6 }  } [get_nets {Ro2[%d].ro/ring_delay8}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {Ro2[%d].ro/ring_delay2}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {Ro2[%d].ro/ring_delay4}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX11 CLBLM_M_A4 }  } [get_nets {Ro2[%d].ro/ring_delay6}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX4 CLBLM_M_A6 }  IMUX12 CLBLM_M_B6 }  } [get_nets {Ro2[%d].ro/ring_invert}]\n" % j)      

for j in range(size_row*2+1,size_row*3+1):
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX32 CLBLM_M_C1 }  } [get_nets {Ro3[%d].ro/reset}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {Ro3[%d].ro/ring_delay1}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {Ro3[%d].ro/ring_delay3}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {Ro3[%d].ro/ring_delay5}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {Ro3[%d].ro/ring_delay7}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX35 CLBLM_M_C6 }  } [get_nets {Ro3[%d].ro/ring_delay8}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {Ro3[%d].ro/ring_delay2}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {Ro3[%d].ro/ring_delay4}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX11 CLBLM_M_A4 }  } [get_nets {Ro3[%d].ro/ring_delay6}]\n" % j)
    fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX4 CLBLM_M_A6 }  IMUX12 CLBLM_M_B6 }  } [get_nets {Ro3[%d].ro/ring_invert}]\n" % j)      

fp.write("\n")

for j in range(1,size_row+1):
    for i in range(2,20+1):
        if (i==4):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX32 CLBLM_M_C1 }  } [get_nets {R1[%d].a1[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX35 CLBLM_M_C6 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX11 CLBLM_M_A4 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX4 CLBLM_M_A6 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R1[%d].a1[%d].ro/ring_invert}]\n" % (j,i))            
        elif(i==2 or i==3):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L32 CLBLM_M_C1 }  } [get_nets {R1[%d].a1[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L35 CLBLM_M_C6 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L11 CLBLM_M_A4 }  } [get_nets {R1[%d].a1[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX_L4 CLBLM_M_A6 }  IMUX_L12 CLBLM_M_B6 }  } [get_nets {R1[%d].a1[%d].ro/ring_invert}]\n" % (j,i))
        elif (i==5 or i==7 or i==13):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX_L29 CLBLL_LL_C2 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX_L35 CLBLL_LL_C6 } } [get_nets {R1m[%d].a1m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX_L11 CLBLL_LL_A4 }  IMUX_L12 CLBLL_LL_B6 }  } [get_nets {R1m[%d].a1m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==15 or i==17 or i==19):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLL_LL_C2 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLL_LL_C6 } } [get_nets {R1m[%d].a1m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLL_LL_A4 }  IMUX12 CLBLL_LL_B6 }  } [get_nets {R1m[%d].a1m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==6 or i==8 or i==10 or i==11 ):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLM_M_C2 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLM_M_C6 } } [get_nets {R1m[%d].a1m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLM_M_A4 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R1m[%d].a1m[%d].ro/ring_invert}]\n" % (j,i))
        else:
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLM_M_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLM_M_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLM_M_A4 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SR1BEG2 IMUX_L29 CLBLM_M_C2 }} [get_nets {R1m[%d].a1m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX_L35 CLBLM_M_C6 } } [get_nets {R1m[%d].a1m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX_L11 CLBLM_M_A4 }  IMUX_L12 CLBLM_M_B6 }  } [get_nets {R1m[%d].a1m[%d].ro/ring_invert}]\n" % (j,i))

for j in range(1,size_row+1):
    for i in range(21,26+1):
        if(i == 21 or i == 22):                       
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L32 CLBLM_M_C1 }  } [get_nets {R11m[%d].a11m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L35 CLBLM_M_C6 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L11 CLBLM_M_A4 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX_L4 CLBLM_M_A6 }  IMUX_L12 CLBLM_M_B6 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==23):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX32 CLBLM_M_C1 }  } [get_nets {R11m[%d].a11m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX35 CLBLM_M_C6 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX11 CLBLM_M_A4 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX4 CLBLM_M_A6 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R11m[%d].a11m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==24):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLL_LL_C2 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLL_LL_C6 } } [get_nets {R111m[%d].a111m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLL_LL_A4 }  IMUX12 CLBLL_LL_B6 }  } [get_nets {R111m[%d].a111m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==25 or i == 27):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX_L29 CLBLL_LL_C2 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX_L35 CLBLL_LL_C6 } } [get_nets {R111m[%d].a111m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX_L11 CLBLL_LL_A4 }  IMUX_L12 CLBLL_LL_B6 }  } [get_nets {R111m[%d].a111m[%d].ro/ring_invert}]\n" % (j,i))            
        elif(i==26):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLM_M_C2 }} [get_nets {R111m[%d].a111m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLM_M_C6 } } [get_nets {R111m[%d].a111m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLM_M_A4 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R111m[%d].a111m[%d].ro/ring_invert}]\n" % (j,i))           

fp.write("\n")

for j in range(size_row+1,size_row*2+1):
    for i in range(2,20+1):
        if ( i==4):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX32 CLBLM_M_C1 }  } [get_nets {R2[%d].a2[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX35 CLBLM_M_C6 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX11 CLBLM_M_A4 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX4 CLBLM_M_A6 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R2[%d].a2[%d].ro/ring_invert}]\n" % (j,i))            
        elif( i==2 or i==3):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L32 CLBLM_M_C1 }  } [get_nets {R2[%d].a2[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L35 CLBLM_M_C6 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L11 CLBLM_M_A4 }  } [get_nets {R2[%d].a2[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX_L4 CLBLM_M_A6 }  IMUX_L12 CLBLM_M_B6 }  } [get_nets {R2[%d].a2[%d].ro/ring_invert}]\n" % (j,i))
        elif (i==5 or i==7 or i==13):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX_L29 CLBLL_LL_C2 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX_L35 CLBLL_LL_C6 } } [get_nets {R2m[%d].a2m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX_L11 CLBLL_LL_A4 }  IMUX_L12 CLBLL_LL_B6 }  } [get_nets {R2m[%d].a2m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==15 or i==17 or i==19):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLL_LL_C2 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLL_LL_C6 } } [get_nets {R2m[%d].a2m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLL_LL_A4 }  IMUX12 CLBLL_LL_B6 }  } [get_nets {R2m[%d].a2m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==6 or i==8 or i==10 or i==11 ):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLM_M_C2 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLM_M_C6 } } [get_nets {R2m[%d].a2m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLM_M_A4 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R2m[%d].a2m[%d].ro/ring_invert}]\n" % (j,i))
        else:
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLM_M_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLM_M_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLM_M_A4 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SR1BEG2 IMUX_L29 CLBLM_M_C2 }} [get_nets {R2m[%d].a2m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX_L35 CLBLM_M_C6 } } [get_nets {R2m[%d].a2m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX_L11 CLBLM_M_A4 }  IMUX_L12 CLBLM_M_B6 }  } [get_nets {R2m[%d].a2m[%d].ro/ring_invert}]\n" % (j,i))

for j in range(size_row+1,size_row*2+1):
    for i in range(21,26+1):
        if(i == 21 or i == 22):                       
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L32 CLBLM_M_C1 }  } [get_nets {R22m[%d].a22m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L35 CLBLM_M_C6 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L11 CLBLM_M_A4 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX_L4 CLBLM_M_A6 }  IMUX_L12 CLBLM_M_B6 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==23):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX32 CLBLM_M_C1 }  } [get_nets {R22m[%d].a22m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX35 CLBLM_M_C6 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX11 CLBLM_M_A4 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX4 CLBLM_M_A6 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R22m[%d].a22m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==24):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLL_LL_C2 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLL_LL_C6 } } [get_nets {R222m[%d].a222m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLL_LL_A4 }  IMUX12 CLBLL_LL_B6 }  } [get_nets {R222m[%d].a222m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==25 or i == 27):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX_L29 CLBLL_LL_C2 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX_L35 CLBLL_LL_C6 } } [get_nets {R222m[%d].a222m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX_L11 CLBLL_LL_A4 }  IMUX_L12 CLBLL_LL_B6 }  } [get_nets {R222m[%d].a222m[%d].ro/ring_invert}]\n" % (j,i))            
        elif(i==26):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLM_M_C2 }} [get_nets {R222m[%d].a222m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLM_M_C6 } } [get_nets {R222m[%d].a222m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLM_M_A4 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R222m[%d].a222m[%d].ro/ring_invert}]\n" % (j,i))           

fp.write("\n")

for j in range(size_row*2+1,size_row*3+1):
    for i in range(2,20+1):
        if ( i==4):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX32 CLBLM_M_C1 }  } [get_nets {R3[%d].a3[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX35 CLBLM_M_C6 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX11 CLBLM_M_A4 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX4 CLBLM_M_A6 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R3[%d].a3[%d].ro/ring_invert}]\n" % (j,i))            
        elif( i==2 or i==3):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L32 CLBLM_M_C1 }  } [get_nets {R3[%d].a3[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L35 CLBLM_M_C6 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L11 CLBLM_M_A4 }  } [get_nets {R3[%d].a3[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX_L4 CLBLM_M_A6 }  IMUX_L12 CLBLM_M_B6 }  } [get_nets {R3[%d].a3[%d].ro/ring_invert}]\n" % (j,i))
        elif (i==5 or i==7 or i==13):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX_L29 CLBLL_LL_C2 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX_L35 CLBLL_LL_C6 } } [get_nets {R3m[%d].a3m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX_L11 CLBLL_LL_A4 }  IMUX_L12 CLBLL_LL_B6 }  } [get_nets {R3m[%d].a3m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==15 or i==17 or i==19):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLL_LL_C2 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLL_LL_C6 } } [get_nets {R3m[%d].a3m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLL_LL_A4 }  IMUX12 CLBLL_LL_B6 }  } [get_nets {R3m[%d].a3m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==6 or i==8 or i==10 or i==11 ):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLM_M_C2 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLM_M_C6 } } [get_nets {R3m[%d].a3m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLM_M_A4 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R3m[%d].a3m[%d].ro/ring_invert}]\n" % (j,i))
        else:
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLM_M_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLM_M_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLM_M_A4 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SR1BEG2 IMUX_L29 CLBLM_M_C2 }} [get_nets {R3m[%d].a3m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX_L35 CLBLM_M_C6 } } [get_nets {R3m[%d].a3m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX_L11 CLBLM_M_A4 }  IMUX_L12 CLBLM_M_B6 }  } [get_nets {R3m[%d].a3m[%d].ro/ring_invert}]\n" % (j,i))

for j in range(size_row*2+1,size_row*3+1):
    for i in range(21,26+1):
        if(i == 21 or i == 22):                       
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L32 CLBLM_M_C1 }  } [get_nets {R33m[%d].a33m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX_L25 CLBLM_L_B5 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX_L24 CLBLM_M_B5 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L35 CLBLM_M_C6 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L10 CLBLM_L_A4 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX_L11 CLBLM_M_A4 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX_L4 CLBLM_M_A6 }  IMUX_L12 CLBLM_M_B6 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==23):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX32 CLBLM_M_C1 }  } [get_nets {R33m[%d].a33m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX35 CLBLM_M_C6 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SL1BEG1 IMUX11 CLBLM_M_A4 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NN2BEG2 IMUX4 CLBLM_M_A6 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R33m[%d].a33m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==24):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX24 CLBLL_LL_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLL_LL_A4 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLL_LL_C2 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLL_LL_C6 } } [get_nets {R333m[%d].a333m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLL_LL_A4 }  IMUX12 CLBLL_LL_B6 }  } [get_nets {R333m[%d].a333m[%d].ro/ring_invert}]\n" % (j,i))
        elif(i==25 or i == 27):
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SL1BEG1 IMUX_L11 CLBLL_LL_A4 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SR1BEG2 IMUX_L29 CLBLL_LL_C2 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX_L35 CLBLL_LL_C6 } } [get_nets {R333m[%d].a333m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX_L11 CLBLL_LL_A4 }  IMUX_L12 CLBLL_LL_B6 }  } [get_nets {R333m[%d].a333m[%d].ro/ring_invert}]\n" % (j,i))            
        elif(i==26):
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay1}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay3}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay5}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay7}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay2}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay4}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 IMUX11 CLBLM_M_A4 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay6}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SR1BEG2 IMUX29 CLBLM_M_C2 }} [get_nets {R333m[%d].a333m[%d].ro/ring_delay8}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 NL1BEG_N3 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLM_M_C6 } } [get_nets {R333m[%d].a333m[%d].ro/reset}]\n" % (j,i))
            fp.write("set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NR1BEG1 IMUX11 CLBLM_M_A4 }  IMUX12 CLBLM_M_B6 }  } [get_nets {R333m[%d].a333m[%d].ro/ring_invert}]\n" % (j,i))           

fp.write("\n")

fp.close()

