# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Tianhe/Desktop/HIT_project/ro64_7z030/bramloc.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cmcs_ro || ORIG_REF_NAME==cmcs_ro}]

# XDC: C:/Users/Tianhe/Desktop/HIT_project/ro64_7z030/fixed_route.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ro_array || ORIG_REF_NAME==ro_array}]

# XDC: C:/Users/Tianhe/Desktop/HIT_project/ro64_7z030/lock_pins.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ring_osc || ORIG_REF_NAME==ring_osc}]

# XDC: C:/Users/Tianhe/Desktop/HIT_project/ro64_7z030/lock_pinsm.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ring_oscm || ORIG_REF_NAME==ring_oscm}]

# XDC: C:/Users/Tianhe/Desktop/HIT_project/ro64_7z030/system_loc.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: bd/design_1/ip/design_1_ring_osc_0_0/design_1_ring_osc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ring_osc_0_0 || ORIG_REF_NAME==design_1_ring_osc_0_0}]

# IP: bd/design_1/ip/design_1_processing_system7_0_axi_periph_0/design_1_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==design_1_processing_system7_0_axi_periph_0}]

# IP: bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_50M_0}]

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0}]

# XDC: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_50M_0}]

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_50M_0}]

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
